### PR TITLE
Update zlib to 1.2.13

### PR DESCRIPTION
**Pull request by starg2**
With a security fix.

### CODE REVIEW

**Comment by JohannesKauffmann** [comment]
I just hit this issue; currently it tries to pull 1.2.12 from an URL which doesn't exist anymore.

While it is good that this is updated to the latest version, maybe it would be better to change the URL to the GitHub releases URL so that the script can still pull older versions, in case the URL changes again. Because AFAICS, zlib.net does not provide older releases, and currently the script breaks with a 404.

`https://github.com/madler/zlib/archive/refs/tags/v1.2.12.tar.gz`
vs:
`https://github.com/madler/zlib/archive/refs/tags/v1.2.13.tar.gz`
Both work.

However, this works:
`https://zlib.net/zlib-1.2.13.tar.gz`
while this doesn't anymore:
`https://zlib.net/zlib-1.2.12.tar.gz`

**Comment by niXman** [comment]
@JohannesKauffmann PR are welcome! ;)

**Comment by JohannesKauffmann** [comment]
See #620.

**Comment by niXman** [comment]
@JohannesKauffmann I see, merged!

this PR was merged too with conflict resolved manually.
thank you @starg2 !

**Comment by starg2** [comment]
@niXman Hmm..., it looks like you've merged `niXman:develop` into `starg2:update-zlib` rather than the other way around?

**Comment by niXman** [comment]
ohh, you are right!
so what should I do next? =)

**Comment by JohannesKauffmann** [comment]
I'd reset this branch to `5b9824aff30ba604a59f640c45b456e7bb5ad3a4`, then interactive rebase on `develop` while resolving the conflicts. Then this can be merged into master, and the commit will be on top of current develop HEAD.

**Comment by starg2** [comment]
@niXman I have rebased `starg2:update-zlib` so you can simply merge it and everything will be ok.

**Comment by niXman** [comment]
done, thanks!

**Pull request merged**
