### PR TITLE
Add mingw-w64 v12.0.0 etc

### LINKED ISSUE #676: ar.exe: could not create temporary file whilst writing archive: no more archived files
Hello,
during usage of pre-built mingw, I encountered issue with `ar.exe`. 

**Issue:**
There seems to be an issue with the `ar.exe` tool in the msys package. I used [x86_64-13.2.0-release-posix-seh-msvcrt-rt_v11-rev0.7z](https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/x86_64-13.2.0-release-posix-seh-msvcrt-rt_v11-rev0.7z) package variant.

**Information:**
- Compilation failures occur randomly.
- The error message points to a failure in `ar.exe`.
- The failure occurs during static linking - I didn't experience similar fail during dynamic linking.

**Failure:**
- ```msys2\mingw64\bin\ar.exe: could not create temporary file whilst writing archive: no more archived files```

**Possibly related links:**
[Qt Forum Discussion](https://forum.qt.io/topic/154922/build-failed-when-use-static-6-5-3-6-6-2-windows-ar-exe-could-not-create-temporary-file-whilst-writing-archive-no-more-archived-files)
[OSDN](https://osdn.net/projects/mingw/lists/archive/users/2019-January/000224.html)
[OSDN-2](https://osdn.net/projects/mingw/lists/archive/users/2019-January/000215.html)

Am I doing something wrong? Is this known bug? It does not happen very often and on rerun it succeeds. Unfortunately as of now, I am not able to produce minimal example where it would be reproducible in at least 1/100 runs or so.

### PR DESCRIPTION
**Pull request by starg2**
Host toolchains built with v12.0.0 should fix #676.

### CODE REVIEW

**Comment by mati865** [comment]
Could you edit the description to mention this is only a prerequisite to fixing #676?

**Comment by niXman** [comment]
@starg2 

im so sorry for the delay, but my email provider puts all my emails from github.com into spam folder and marks it as read! oO

btw.
> This branch has conflicts that must be resolved

**Comment by starg2** [comment]
The PR has been rebased and is ready for merge.

**Comment by mati865** [comment]
Would it be possible to release a new version bootstrapped with this PR (so with the builder using mingw-w64 v12.0.0 based toolchain to build a new mingw-w64 v12.0.0 based toolchain) to fix https://github.com/niXman/mingw-builds/issues/676?
Thanks in advance

**Pull request merged**
