### PR TITLE
Prefer https over insecure protocols

### PR DESCRIPTION
**Pull request by starg2**
This PR replaces insecure protocols (ftp, git, http) with https.

### CODE REVIEW

**Comment by niXman** [comment]
hi,

isn't git an encrypted protocol? could you provide a proof, plz?

**Comment by niXman** [comment]
nevertheless, merged.

thanks!

**Comment by starg2** [comment]
> isn't git an encrypted protocol?

Only if it's paired with ssh. However, ssh doesn’t support anonymous access so it's not suitable for just downloading code.

[On the Git protocol side, unencrypted git:// offers no integrity or authentication, making it subject to tampering.](https://github.blog/2021-09-01-improving-git-protocol-security-github/)

**Comment by niXman** [comment]
got it, many thanks for explanation!

**Comment by niXman** [comment]
@starg2  some strange error occurs now when `libcloog` downloading:
```
--2022-09-07 15:36:07--  https://www.bastoul.net/cloog/pages/download/cloog-0.18.4.tar.gz
Resolving www.bastoul.net (www.bastoul.net)... 62.210.16.62
Connecting to www.bastoul.net (www.bastoul.net)|62.210.16.62|:443... connected.
OpenSSL: error:0A000438:SSL routines::tlsv1 alert internal error
Unable to establish SSL connection.
```

any ideas?

**Comment by starg2** [comment]
I didn't encounter such an error when I wrote the patch several months ago. But now I have the same error. This is strange indeed.

There is probably nothing we can do other than reverting the problematic URL to `http://`.

**Comment by niXman** [comment]
don't worry, I already found another website with the sources and it works: https://github.com/niXman/mingw-builds/blob/cross-build/scripts/cloog.sh#L43

will merge that branch a bit later.

thanks!

**Pull request merged**
