### PR TITLE
build: use eval to allow for tilde expansion

### LINKED ISSUE #618: --buildroot does not recognize ~ as msys home directory
Running `./build ... --buildroot=~/builddir` results in a `'~'` folder inside of the git clone, which has the `builddir` folder inside it.

Just something I noticed while running the script. Maybe I should've specified the absolute path, I don't know.

### PR DESCRIPTION
**Pull request by JohannesKauffmann**
Paths with spaces don't work, however. Document this.

Fixes #618.

### CODE REVIEW

**Comment by niXman** [comment]
merged, thanks!

please close the relevant ticket too.

**Comment by JohannesKauffmann** [comment]
eeeee...

I'm not sure I've done it right, and also not sure it was a great idea to merge this without letting the CI pass..

Looking at the Github jobs, it seems I've done an oopsie.

**Comment by niXman** [comment]
I see =)

any ideas about a correct fix?

**Comment by JohannesKauffmann** [comment]
Not yet.

Maybe better to revert this first, in order not to break everyone.

**Comment by niXman** [comment]
ah, you already did it.

**Comment by JohannesKauffmann** [comment]
#626 should fix it.

**Pull request merged**
