### PR TITLE
Fix/boostrap by default

### PR DESCRIPTION
**Pull request by theodelrieu**
@niXman Finally it wasn't that difficult, once I stumbled upon `library/config.sh`

### CODE REVIEW

**Comment by theodelrieu** [comment]
Unrelated to this PR, I just realized that `JOBS` defaults to `1`, which is why my build takes 6 hours... It might be a nice improvement to set a reasonable default, e.g. 4?

**Comment by niXman** [comment]
>It might be a nice improvement to set a reasonable default, e.g. 4?

yes, change it please.

**Comment by niXman** [comment]
and remove `--bootstrap` option completely (https://github.com/niXman/mingw-builds/pull/528/commits/25e1e2f91a9372d15163800da8d32ec85ffcdaf0#diff-b0da275520918e23dd615e2a747528f1L62)

**Comment by theodelrieu** [comment]
@niXman done

**Comment by niXman** [comment]
@theodelrieu please fix the indentation here: https://github.com/niXman/mingw-builds/pull/528/commits/92465987c538d409cb10a2f132345c76474bd7b0#diff-b0da275520918e23dd615e2a747528f1R69

**Comment by niXman** [comment]
merged, thank you!

**Pull request merged**
