### PR TITLE
Updates

### LINKED ISSUE #472: build fails at tcl
Hi there,

On a Win10 machine with MSYS2 64bit shell i ran the following command to build the toolchain:

`./build --mode=gcc-7.2.0 --jobs=10 --arch=x86_64 --bootstrap`

Everything worked until tcl

> -> tcl
> ---> tcl8.6.9-src.tar.gz downloaded
> ---> tcl8.6.9-src.tar.gz unpacked
> ---> patched
> ---> after_patch executed
> ---> configured
> ---> built
> --> installing...
> error!

I've attached the error log that popped up.
[tcl-error.log](https://github.com/niXman/mingw-builds/files/3019530/tcl-error.log)

If there is a workaround, please let me know!

### PR DESCRIPTION
**Pull request by Furniel**
- fixed tcl build failures on some systems (should fix #472)
- replaced  -static-libgcc tcl patch with universal fix
- gcc-ar, gcc-nm, gcc-ranlib enebled for lto builds(this fixes many lto build errors, but not all)
- gdb 8.3
- expat 2.2.7
- openssl 1.0.2s
- sqlite 3290000
- readme updated

### CODE REVIEW

**Comment by niXman** [comment]
Thank you!

**Comment by Eric-Vignola** [comment]
thanks! i'll get latest and will let you know if it fixes #472
<https://github.com/niXman/mingw-builds/issues/472>

**Comment by niXman** [comment]
@Eric-Vignola any news?

**Comment by Eric-Vignola** [comment]
Had to do a fresh install of msys (new machine). i just launched the build,
will report back shortly

**Comment by Eric-Vignola** [comment]
Good news, it did get pass tcl!

Bad news: there's still one error at the "lto_test.exe" phase


-> tests
--> Doesn't need to download
--> Unpack doesn't need
--> gcc      x86_64: "omp_test.c" ...             -> 0 -> done
--> execute x86_64: "omp_test.exe" ...            -> 0 -> done
--> gcc      i686: "omp_test.c" ...               -> 0 -> done
--> execute i686: "omp_test.exe" ...              -> 0 -> done
--> gcc      x86_64: "time_test.c" ...            -> 0 -> done
--> execute x86_64: "time_test.exe" ...           -> 0 -> done
--> gcc      i686: "time_test.c" ...              -> 0 -> done
--> execute i686: "time_test.exe" ...             -> 0 -> done
--> g++     x86_64: "filesystem.cpp" ...          -> 0 -> done
--> execute x86_64: "filesystem.exe" ...          -> 0 -> done
--> g++     i686: "filesystem.cpp" ...            -> 0 -> done
--> execute i686: "filesystem.exe" ...            -> 0 -> done
--> g++     x86_64: "lasterror_test2.cpp" ...     -> 0 -> done
--> execute x86_64: "lasterror_test2.exe" ...     -> 0 -> done
--> g++     i686: "lasterror_test2.cpp" ...       -> 0 -> done
--> execute i686: "lasterror_test2.exe" ...       -> 0 -> done
--> g++     x86_64: "lasterror_test1.cpp" ...     -> 0 -> done
--> execute x86_64: "lasterror_test1.exe" ...     -> 0 -> done
--> g++     i686: "lasterror_test1.cpp" ...       -> 0 -> done
--> execute i686: "lasterror_test1.exe" ...       -> 0 -> done
--> g++     x86_64: "random_device.cpp" ...       -> 0 -> done
--> execute x86_64: "random_device.exe" ...       -> 0 -> done
--> g++     i686: "random_device.cpp" ...         -> 0 -> done
--> execute i686: "random_device.exe" ...         -> 0 -> done
--> g++     x86_64: "dll1.cpp" ...                -> 0 -> done
--> g++     x86_64: "dll_test1.cpp" ...           -> 0 -> done
--> execute x86_64: "dll_test1.exe" ...           -> 0 -> done
--> g++     i686: "dll1.cpp" ...                  -> 0 -> done
--> g++     i686: "dll_test1.cpp" ...             -> 0 -> done
--> execute i686: "dll_test1.exe" ...             -> 0 -> done
--> g++     x86_64: "lto_int.cpp" ...             -> 0 -> done
--> g++     x86_64: "lto_test.cpp" ...            -> 0 -> done
--> g++      x86_64: "lto_test.exe" ...           -> 0 -> done
--> execute x86_64: "lto_test.exe" ...            -> 0 -> done
--> g++     i686: "lto_int.cpp" ...               -> 0 -> done
--> g++     i686: "lto_test.cpp" ...              -> 0 -> done
--> g++      i686: "lto_test.exe" ...
-> 1 -> error. terminate.


Error log: lto_int.o-link.log
g++ -s -m32 lto_int.o lto_test.o -flto -o lto_test.exe
lto_int.o: file not recognized: file format not recognized
collect2.exe: error: ld returned 1 exit status

**Comment by niXman** [comment]
please show the cmdline you run.

**Comment by Eric-Vignola** [comment]
Here's the full chain of events from a clean msys install

# install msys2
msys2-x86_64-20190524.exe

# update msys2
pacman -Syuu

#  terminate shell, relaunch msys-64 shell
pacman -Suu

# install build requirements
pacman -S git subversion tar zip p7zip make patch automake autoconf libtool
bison gettext-devel sshpass texinfo autogen dejagnu

# download mingw-builds/develop
git clone https://github.com/niXman/mingw-builds.git
cd mingw-builds
git checkout develop

# launch the build
./build --mode=gcc-7.2.0 --jobs=10 --arch=x86_64 --bootstrap

**Comment by niXman** [comment]
@Eric-Vignola and? the same error `lto_int.o: file not recognized: file format not recognized` ?

**Comment by Eric-Vignola** [comment]
correct

g++ -s -m32 lto_int.o lto_test.o -flto -o lto_test.exe
lto_int.o: file not recognized: file format not recognized
collect2.exe: error: ld returned 1 exit status

**Comment by niXman** [comment]
it only means LTO does not work...

just comment out this(https://github.com/niXman/mingw-builds/blob/develop/scripts/tests.sh#L113) line and restart the script

**Comment by Eric-Vignola** [comment]
ok i can do that but may not be necessary: last night i repeated my clean
build steps and ran the build command with a few more flags:

./build --mode=gcc-7.2.0 --jobs=10 --arch=x86_64 --bootstrap
--exceptions=seh --rt-version=trunk --threads=win32
--enable-languages=c,c++,fortran --bootstrap

and it built with no issues. I presume one of these flags fixed the issue.
Not sure which.

**Comment by niXman** [comment]
yes, any of these flags could affect: --exceptions=seh --rt-version=trunk --threads=win32

**Comment by Furniel** [comment]
It's old bug i686: "lto_test.exe" fails with sjlj(MULTILIB enabled by default) exceptions in x86_64 build. Not sure why so not fixed. If there is no need in multilib and you really need sjlj(why? they are slow.) --no-multilib flag should help.

**Comment by Eric-Vignola** [comment]
understood.

question: is it possible to add msvcr140 as an option for
--with-default-msvcrt ?

**Pull request merged**
